name: eventpod
description: The best a dev can get
version: 0.0.6
homepage:

environment:
  sdk: '>=3.1.4 <4.0.0'
  flutter: ">=3.13.8"

dependencies:
  flutter:
    sdk: flutter

  hooks_riverpod: ^2.4.4
  logger: ^2.0.2+1
  duration: ^3.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# The following section is specific to Flutter.
flutter:

  
